export const charactersData = [
  {
    id: "1",
    englishName: "Monkey D. Luffy",
    japaneseName: "モンキー・D・ルフィ",
    birthday: "May 5",
    lastKnownLocation: "Egghead",
    bounty: "3,000,000,000",
    devilFruitName: "Hito Hito no Mi, Model: Nika",
    avatarSrc: "/luffy.png",
    description: "Capitán de los Piratas del Sombrero de Paja y uno de los Cuatro Emperadores.",
    role: "Capitán",
    abilities: ["Gear 2", "Gear 3", "Gear 4", "Gear 5", "Haki Observación", "Haki de Armadura", "Haki del Rey", "Gomu Gomu no Bajrang Gun", "Visión de futuro"],
    weaknesses: ["No puede nadar", "Agotamiento tras Gear 5", "Extrema imprudencia", "Dependencia alimenticia"]
  },
  {
    id: "2",
    englishName: "Roronoa Zoro",
    japaneseName: "ロロノア・ゾロ",
    birthday: "November 11",
    lastKnownLocation: "Egghead",
    bounty: "1,111,000,000",
    devilFruitName: "Ninguna",
    avatarSrc: "/zoro.png",
    description: "Espadachín maestro que busca convertirse en el mejor del mundo.",
    role: "Espadachín",
    abilities: ["Estilo de tres espadas", "Haki de Armadura", "Haki de Observación", "Ashura", "Enma"],
    weaknesses: ["Sentido de la orientación nulo", "Consumo excesivo de alcohol", "Heridas autoinfligidas por Enma"]
  },
  {
    id: "3",
    englishName: "Nami",
    japaneseName: "ナミ",
    birthday: "July 3",
    lastKnownLocation: "Egghead",
    bounty: "366,000,000",
    devilFruitName: "Ninguna",
    avatarSrc: "/nami.png",
    description: "Navegante excepcional que busca dibujar un mapa de todo el mundo.",
    role: "Navegante",
    abilities: ["Clima-Tact", "Zeus", "Manipulación meteorológica", "Navegación experta"],
    weaknesses: ["Fuerza física limitada", "Avaricia excesiva", "Vulnerabilidad defensiva sin Zeus"]
  },
  {
    id: "4",
    englishName: "Vinsmoke Sanji",
    japaneseName: "ヴィンスモーク・サンジ",
    birthday: "March 2",
    lastKnownLocation: "Egghead",
    bounty: "1,032,000,000",
    devilFruitName: "Ninguna",
    avatarSrc: "/sanji.png",
    description: "Chef de la tripulación y maestro del combate con las piernas.",
    role: "Cocinero",
    abilities: ["Ifrit Jambe", "Diable Jambe", "Exoesqueleto Germa", "Velocidad sobrehumana"],
    weaknesses: ["Incapacidad de golpear mujeres", "Perversión extrema", "Pérdida de emociones (riesgo por genes)"]
  },
  {
    id: "5",
    englishName: "Usopp",
    japaneseName: "ウソップ",
    birthday: "April 1",
    lastKnownLocation: "Egghead",
    bounty: "500,000,000",
    devilFruitName: "Ninguna",
    avatarSrc: "/usopp.png",
    description: "Francotirador experto y el alma creativa del equipo.",
    role: "Francotirador",
    abilities: ["Pop Greens", "Kabuto Negro", "Haki de Observación (despierto)", "Tácticas de engaño"],
    weaknesses: ["Cobardía crónica", "Baja autoestima", "Dependencia de proyectiles"]
  },
  {
    id: "6",
    englishName: "Tony Tony Chopper",
    japaneseName: "トニートニー・チョッパー",
    birthday: "December 24",
    lastKnownLocation: "Egghead",
    bounty: "1,000",
    devilFruitName: "Hito Hito no Mi",
    avatarSrc: "/chopper.png",
    description: "Médico de la tripulación que busca curar todas las enfermedades.",
    role: "Médico",
    abilities: ["Rumble Ball", "Monster Point", "Conocimientos médicos avanzados", "Comunicación animal"],
    weaknesses: ["Ingenuidad", "Dependencia de Rumble Balls", "Miedo a situaciones de alto riesgo"]
  },
  {
    id: "7",
    englishName: "Nico Robin",
    japaneseName: "ニコ・ロビン",
    birthday: "February 6",
    lastKnownLocation: "Egghead",
    bounty: "930,000,000",
    devilFruitName: "Hana Hana no Mi",
    avatarSrc: "/robin.png",
    description: "Arqueóloga que puede leer los Poneglyphs.",
    role: "Arqueóloga",
    abilities: ["Cuerpo floreciente", "Gigante Fleur", "Demonio Fleur", "Conocimiento histórico"],
    weaknesses: ["Dolor compartido (si dañan sus extremidades florecidas)", "No puede luchar bajo el agua"]
  },
  {
    id: "8",
    englishName: "Franky",
    japaneseName: "フランキー",
    birthday: "March 9",
    lastKnownLocation: "Egghead",
    bounty: "394,000,000",
    devilFruitName: "Ninguna",
    avatarSrc: "/franky.png",
    description: "Carpintero naval y genio de la tecnología cyborg.",
    role: "Carpintero",
    abilities: ["General Franky", "Láseres de Vegapunk", "Modificación cíborg", "Reparación naval"],
    weaknesses: ["Dependencia de suministro de Cola", "Espalda vulnerable", "Tamaño voluminoso"]
  },
  {
    id: "9",
    englishName: "Brook",
    japaneseName: "ブルック",
    birthday: "April 3",
    lastKnownLocation: "Egghead",
    bounty: "383,000,000",
    devilFruitName: "Yomi Yomi no Mi",
    avatarSrc: "/brook.png",
    description: "Músico y espadachín que regresó de la muerte.",
    role: "Músico",
    abilities: ["Soul Solid", "Manipulación de almas", "Velocidad de ataque", "Caminar sobre el agua"],
    weaknesses: ["Fragilidad ósea", "Vulnerable al humor absurdo", "No puede nadar"]
  },
  {
    id: "10",
    englishName: "Jinbe",
    japaneseName: "ジンベエ",
    birthday: "April 2",
    lastKnownLocation: "Egghead",
    bounty: "1,100,000,000",
    devilFruitName: "Ninguna",
    avatarSrc: "/jinbe.png",
    description: "Timonel experto y ex-Shichibukai.",
    role: "Timonel",
    abilities: ["Karate Gyojin", "Control del agua", "Haki de Armadura", "Resistencia sobrehumana"],
    weaknesses: ["Necesidad de estar cerca de fuentes de agua para maximizar su poder"]
  }
];
